# Generated by Django 6.0.2 on 2026-04-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
